web:
  build: ./web
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - "./web/apache:/etc/apache2/sites-enabled"
    - "../:/var/www/html"
  links:
    - db

db:
  image: mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_DATABASE: dev
  volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf

phpmyadmin:
  image: phpmyadmin/phpmyadmin
  ports:
    - "8080:80"
  environment:
    PMA_HOST: db
    PMA_PORT: 3306
    PMA_USER: root
    PMA_PASSWORD: 123456
    MYSQL_ROOT_PASSWORD: 123456
  links:
    - db
